Repository johanmazoyer/Asterix, pull requests merged in 2022-11, with the labels that each got.

#97 Fix tests
  Asterix/tests/test_propagations.py
  Asterix/tests/test_pupil.py
Labels: CI

#101 Fix zoom-in-sampling function for coronagraph propagations
  Asterix/optics/propagation_functions.py
  Asterix/tests/test_coronagraph.py
  notebooks/zoom-in_sampling_coro.ipynb
Labels: bug, coronagraphs

#103 Enable zoom-in sampling for Asterix
  Asterix/optics/propagation_functions.py
  Asterix/tests/test_propagations.py
  notebooks/coronagraph_propagation.ipynb
  notebooks/zoom-in_sampling_coro.ipynb
Labels: coronagraphs, CI

#94 Change the WLs to be equally spaced in a large bandwidth
  Asterix/optics/optical_systems.py
Labels: coronagraphs, correction

#105 Transform exception in warning for number of modes in THD matrices
  Asterix/wfsc/corrector.py
Labels: correction

#107 Add tests propagation
  Asterix/tests/test_propagations.py
Labels: CI

#117 Fix THD2 class import.
  notebooks/beginner-tutorial_optical-components-and-systems.ipynb
Labels: bug
